name 'sssd_ldap'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license          'Apache-2.0'
description      'Sets up SSSD for LDAP on Ubuntu and RHEL systems'
version          '5.2.1'
source_url        'https://github.com/sous-chefs/sssd_ldap'
issues_url        'https://github.com/sous-chefs/sssd_ldap/issues'

supports 'redhat'
supports 'centos'
supports 'amazon'
supports 'scientific'
supports 'oracle'
supports 'ubuntu'
supports 'debian'

chef_version '>= 13'
