name              'sssd_ldap'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides an sssd_ldap resource for LDAP-backed SSSD configuration'
version           '6.0.0'
source_url        'https://github.com/sous-chefs/sssd_ldap'
issues_url        'https://github.com/sous-chefs/sssd_ldap/issues'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 11.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'

chef_version '>= 15.3'
